import { Metadata } from 'next'

export const metadatas: Metadata = {
  title: 'Business Energy Comparison | Save on Gas & Electricity | Ecosave',
  description: 'Compare business utility rates and find the best deals on energy, water, and waste management services.',
  keywords: [
    'business energy comparison',
    'compare business energy',
    'business energy rates UK',
    'compare business energy rates',
    'business electricity comparison',
    'business gas comparison',
    'business energy suppliers UK',
    'cheapest business energy supplier',
    'best business energy deals',
    'business energy quotes',
    'business energy switching',
    'business energy prices UK',
    'compare commercial energy',
    'business electricity rates',
    'business gas rates',
    'business energy tariffs',
    'business energy contracts',
    'business energy broker UK',
    'business energy savings',
    'business energy deals UK',
    'business energy switching service',
    'compare business electricity suppliers',
    'compare business gas suppliers',
    'business energy price comparison',
    'business energy cost calculator',
    'business energy renewal',
    'business energy for SMEs',
    'business energy for large businesses',
    'British Gas business',
    'EDF business energy',
    'E.ON business energy',
    'SSE business energy',
    'ScottishPower business energy',
    'npower business energy',
    'Octopus Energy business',
    'TotalEnergies business',
    'SmartestEnergy business',
    'Crown Gas & Power business',
    'Everflow business energy',
    'best commercial energy supplier UK',
    'switch business energy supplier',
    'business energy comparison site',
    'compare business utility bills',
    'business energy quote online',
  ],
  metadataBase: new URL('https://ecosavegasandpower.com'),
  alternates: {
    canonical: 'https://ecosavegasandpower.com',
  },
  icons: {
    icon: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  },
  openGraph: {
    title: 'Business Energy Comparison | Save on Gas & Electricity | Ecosave',
    description: 'Compare and save on business energy, insurance, connectivity, and finance solutions.',
    url: 'https://ecosavegasandpower.com/',
    siteName: 'Ecosave Gas & Power',
    locale: 'en_GB',
    type: 'website',
  },
  robots: {
    index: true,
    follow: true,
  },
};